ali/ali/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    #1
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),

    #Where can I find OR set theses paths these values
    #2
    path('password_reset_done/',
        auth_views.PasswordResetDoneView.as_view(template_name="email_sent.html"),name="password_reset_done"),
    #3
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),

    #4
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_complete.html"), name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ali/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
	path('posts/', views.posts, name="posts"),
	path('post/<slug:slug>/', views.post, name="post"),
	path('profile/', views.profile, name="profile"),

	#CRUD PATHS

	path('create_post/', views.createPost, name="create_post"),
	path('update_post/<slug:slug>/', views.updatePost, name="update_post"),
	path('delete_post/<slug:slug>/', views.deletePost, name="delete_post"),


	path('send_email/', views.sendEmail, name="send_email"),

	path('login/', views.loginPage, name="login"),
	path('register/', views.registerPage, name="register"),
	path('logout/', views.logoutUser, name="logout"),

	path('account/', views.userAccount, name="account"),
	path('update_profile/', views.updateProfile, name="update_profile"),
]

ali/base/models.py
from django.db import models
from django.contrib.auth.models import User


from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Profile(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=200, blank=True, null=True)
	last_name = models.CharField(max_length=200, blank=True, null=True)
	email = models.CharField(max_length=200)
	profile_pic = models.ImageField(null=True, blank=True, upload_to="images", default="/user.png")
	bio = models.TextField(null=True, blank=True)
	twitter = models.CharField(max_length=200,null=True, blank=True)

	def __str__(self):
		name = str(self.first_name)
		if self.last_name:
			name += ' ' + str(self.last_name)
		return name

class Tag(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name


class Post(models.Model):
	headline = models.CharField(max_length=200)
	sub_headline = models.CharField(max_length=200, null=True, blank=True)
	thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="/images/placeholder.png")
	body = RichTextUploadingField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)
	featured = models.BooleanField(default=False)
	tags = models.ForeignKey(Tag, null=True, blank=True, on_delete=models.CASCADE)
	slug = models.SlugField(null=True, blank=True)

	def __str__(self):
		return self.headline

	def save(self, *args, **kwargs):

		if self.slug == None:
			slug = slugify(self.headline)

			has_slug = Post.objects.filter(slug=slug).exists()
			count = 1
			while has_slug:
				count += 1
				slug = slugify(self.headline) + '-' + str(count)
				has_slug = Post.objects.filter(slug=slug).exists()

			self.slug = slug

		super().save(*args, **kwargs)


class PostComment(models.Model):
	author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
	body = models.TextField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	def __str__(self):
		return self.body

	@property
	def created_dynamic(self):
		now = timezone.now()
		return now

ali/base/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post, Profile


class CustomUserCreationForm(UserCreationForm):

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

class PostForm(ModelForm):

	class Meta:
		model = Post
		fields = '__all__'

		widgets = {
			'tags':forms.CheckboxSelectMultiple(),
		}

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']
		

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'
		exclude = ['user']

ali/base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .decorators import *

from .forms import PostForm, CustomUserCreationForm, ProfileForm, UserForm
from .filters import PostFilter

from .models import *

# Create your views here.

def home(request):
	posts = Post.objects.filter(active=True, featured=True)[0:3]

	context = {'posts':posts}
	return render(request, 'base/index.html', context)

def posts(request):
	posts = Post.objects.filter(active=True)
	myFilter = PostFilter(request.GET, queryset=posts)
	posts = myFilter.qs

	page = request.GET.get('page')

	paginator = Paginator(posts, 5)

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	context = {'posts':posts, 'myFilter':myFilter}
	return render(request, 'base/posts.html', context)

def post(request, slug):
	post = Post.objects.get(slug=slug)

	if request.method == 'POST':
		PostComment.objects.create(
			author=request.user.profile,
			post=post,
			body=request.POST['comment']
			)
		messages.success(request, "You're comment was successfuly posted!")

		return redirect('post', slug=post.slug)


	context = {'post':post}
	return render(request, 'base/post.html', context)

def profile(request):
	return render(request, 'base/profile.html')

#CRUD VIEWS
@admin_only
@login_required(login_url="home")
def createPost(request):
	form = PostForm()

	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
		return redirect('posts')

	context = {'form':form}
	return render(request, 'base/post_form.html', context)


@admin_only
@login_required(login_url="home")
def updatePost(request, slug):
	post = Post.objects.get(slug=slug)
	form = PostForm(instance=post)

	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES, instance=post)
		if form.is_valid():
			form.save()
		return redirect('posts')

	context = {'form':form}
	return render(request, 'base/post_form.html', context)

@admin_only
@login_required(login_url="home")
def deletePost(request, slug):
	post = Post.objects.get(slug=slug)

	if request.method == 'POST':
		post.delete()
		return redirect('posts')
	context = {'item':post}
	return render(request, 'base/delete.html', context)



def sendEmail(request):

	if request.method == 'POST':

		template = render_to_string('base/email_template.html', {
			'name':request.POST['name'],
			'email':request.POST['email'],
			'message':request.POST['message'],
			})

		email = EmailMessage(
			request.POST['subject'],
			template,
			settings.EMAIL_HOST_USER,
			['dennisivy11@gmail.com']
			)

		email.fail_silently=False
		email.send()

	return render(request, 'base/email_sent.html')

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')

	if request.method == 'POST':
		email = request.POST.get('email')
		password =request.POST.get('password')

		#Little Hack to work around re-building the usermodel
		try:
			user = User.objects.get(email=email)
			user = authenticate(request, username=user.username, password=password)
		except:
			messages.error(request, 'User with this email does not exists')
			return redirect('login')
			
		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			messages.error(request, 'Email OR password is incorrect')

	context = {}
	return render(request, 'base/login.html', context)

def registerPage(request):
	form = CustomUserCreationForm()
	if request.method == 'POST':
		form = CustomUserCreationForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.save()
			messages.success(request, 'Account successfuly created!')

			user = authenticate(request, username=user.username, password=request.POST['password1'])

			if user is not None:
				login(request, user)

			next_url = request.GET.get('next')
			if next_url == '' or next_url == None:
				next_url = 'home'
			return redirect(next_url)
		else:
			messages.error(request, 'An error has occured with registration')
	context = {'form':form}
	return render(request, 'base/register.html', context)

def logoutUser(request):
	logout(request)
	return redirect('home')

@login_required(login_url="home")
def userAccount(request):
	profile = request.user.profile

	context = {'profile':profile}
	return render(request, 'base/account.html', context)

@login_required(login_url="home")
def updateProfile(request):
	user = request.user
	profile = user.profile
	form = ProfileForm(instance=profile)
	if request.method == 'POST':
		user_form = UserForm(request.POST, instance=user)
		if user_form.is_valid():
			user_form.save()

		form = ProfileForm(request.POST, request.FILES, instance=profile)
		if form.is_valid():
			form.save()
			return redirect('account')


	context = {'form':form}
	return render(request, 'base/profile_form.html', context)

ali/base/templates/base/account.html
{% include 'base/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	#user_pic{
		height: 200px;
		width: 200px;
		border-radius: 50%;
		border:5px solid #888;
		margin:0 auto;
		object-fit: cover;
	}

	#user-info-box{
		text-align: center;
	}
</style>

<div class="main-container">
	<br>
	<div class="row">
		<div class="col-md-4">
			<div class="card card-body" id="user-info-box">
				<img id="user_pic" src="{{profile.profile_pic.url}}">
				<br>
				<h2>{{profile}}</h2>
				<p>Email: {{profile.email}}</p>
				<hr>
				<p>{{profile.bio}}</p>
				<hr>
				<a class="btn btn-info btn-block" href="{% url 'update_profile' %}">Edit Profile</a>
			</div>
		</div>
		<div class="col-md-8">
			<div class="card card-body">
				<h3>My Orders:</h3>
				<hr>
				<table class="table">
					<thead class="thead-dark">
						<tr>
							<th>Transaction ID</th>
							<th>Date</th>
							<th>Items/Articles</th>
							<th>Total</th>
							<th></th>
						</tr>
					</thead>
					<tr>
						<td>122523462</td>
						<td>11-24-2020</td>
						<td>2</td>
						<td>$12.18</td>
						<td><a class="btn btn-dark btn-sm" href="">View Order</a></td>
					</tr>

					<tr>
						<td>122523123</td>
						<td>11-29-2020</td>
						<td>7</td>
						<td>$53.65</td>
						<td><a class="btn btn-dark btn-sm" href="">View Order</a></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

ali/base/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<div class="main-container">
	<form method="POST" action="">
		{% csrf_token %}

		<p>Etes-vous sûr que vous voulez supprimer {{item}}?</p>
		<a class="btn btn-primary" href="{% url 'posts' %}">&laquo Retour aux articles</a>
		<input class="btn btn-danger" type="submit" value="Confirm">
	</form>
</div>

{% endblock content %}

ali/base/templates/base/email_sent.html
{% extends 'base/main.html' %}

{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Merci d'avoir contacté!</h1>
		<p>Votre message a été envoyé avec succès. Je ferai de mon mieux pour vous répondre dans les meilleurs délais :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">RETOUR À LA PAGE D'ACCUEIL</a>
	</div>
</div>

{% endblock content %}

ali/base/templates/base/email_template.html
{{message}}

{{name}}

{{email}}

ali/base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ali Samba</title>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>


	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm Ali Samba @Baye ali</h1>
			</div>


			<div class="intro-wrapper">
				{% include 'base/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/pp.jpg' %}">
					<h5 style="text-align: center;line-height: 0;">Personnaliser le thème</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Les paramètres du thème seront enregistrés pour<br> votre prochaine visite</p>
				</div>

				<div class="right-column">

					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p>Je suis <b>développeur</b>, maintenancier, câbleur et encadreur en mathématique</p>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>Plus à propos de moi</h4>

					<p>Je passe la plupart du temps à développer des applications basées sur django.</p>

					<p>Je participe sur des projets opensources, cable des réseaux, encadre des élèves et faire plus de recherches  .</p>


					<hr>

					<h4>TOP EXPERTISE</h4>

					<p>Développeur Fullstack avec un focus principal sur Django:: <a target="_blank" href="{% static 'mycv.pdf' %}">Télécharger le CV</a></p>

					<div id="skills">
						<ul>
							<li>Python</li>
							<li>Django</li>
							<li>HTML/CSS</li>
							<li>Linux</li>
							<li>Postgres</li>
						</ul>

						<ul>
							<li>Cablage</li>
							<li>Maintenance</li>
							<li>Inkscape</li>
							<li>Machine learning</li>
							<li>JavaScript</li>
						</ul>

					</div>

				</div>


				<div class="social-links">
					<img id="social_img" src="{% static 'images/follow.jpg' %}">
					<h3>Find me on Twitter & github</h3>

					<a target="_blank" href="https://github.com/alyasamba">github: @alyasamba</a>
					<br>
					<a target="_blank" href="https://twitter.com/SambaAli9">Twitter: @alyasamba</a>
				</div>
			</div>

		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Certains de mes projets passés</h3>

			<div class="post-wrapper">
				{% for post in posts %}
				<div>
					<div class="post">
						<img class="thumbnail" src="{{post.thumbnail.url}}">
						<div class="post-preview">
							<h6 class="post-title">{{post.headline}}</h6>
							<p class="post-intro">{{post.sub_headline}}</p>
							<a href="{%  url 'post' post.slug %}">Read More</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

			<p align="center">
				<a href="{% url 'posts' %}">View More</a>
			</p>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}
				<a name="contact"></a>

				<label>Name</label>
				<input required class="input-field" type="text" name="name">

				<label>Subject</label>
				<input required class="input-field" type="text" name="subject">

				<label>Email</label>
				<input required class="input-field" type="text" name="email">

				<label>Message</label>
				<textarea required class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section>

	<script type="text/javascript">
		let static = "{% static 'css' %}"
	</script>

	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

ali/base/templates/base/login.html
{% include 'base/main.html' %}
{% load static %}
{% block content %}


<section id="login-page-wrapper">
	<div id="login-form-wrapper">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-success" role="alert">
						<span>{{message}}</span>
					</div>
				{% elif message.tags == 'error' %}
					<div class="alert alert-danger" role="alert">
						<span>{{message}}</span>
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}

		<h3 style="text-align: center">Member Login</h3>
		<hr>
		<form method="POST">
			{% csrf_token %}
			<label>Email</label>
			<input class="form-control" type="email" name="email">
			<br>
			<label>Password</label>
			<input class="form-control" type="password" name="password">
			<br>
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="Login">
		</form>

		<br>
		<p>N' avez-vous pas de compte?<a href="{% url 'register' %}">Register</a></p>
		<p>Mot de passe oublié? <a href="{% url 'password_reset' %}">Reset</a></p>
	</div>
</section>

{% endblock content %}

ali/base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ali Samba</title>

	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
</head>
<body>

	{% include 'base/navbar.html' %}

	{% block content %}
	<!-- Content goes here -->
	{% endblock content %}

</body>
</html>

ali/base/templates/base/password_reset.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div class="main-container">
	<h3>Password reset</h3>

	<p>Mot de passe oublié? Entrez votre adresse e-mail ci-dessous et nous vous enverrons par e-mail les instructions pour en définir une nouvelle.</p>


	<form method="POST" action="">
		{% csrf_token %}
		{{form|crispy}}
		<br>
		<input class="btn btn-primary" type="submit" value="Reset my password">
	</form>
</div>

{% endblock content %}

ali/base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	img{
		max-width: 100%;
		object-fit: cover;
	}

	.featured_image{
		margin-top: 20px;
		margin-bottom: 20px;
	}

	.post-container{
			width: 900px;
			margin: 0 auto;
			padding-top: 20px;
			padding-bottom: 20px;
	}

	.comments-wrapper{
		margin-top: 50px;
		padding: 10px;
		border:1px solid var(--borderColor);
		-webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		-moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
	}

	.comment{
		display: flex;
		padding: 15px;
	}

	.comment-author{
		font-size: 14px;
		font-weight: 700;
		color: rgb(30, 174, 219) !important;
		margin: 2px;
	}

	.author-pic{
		width: 50px;
		height: 50px;
		border-radius: 50%;
		margin-right: 10px;
	}

	.comment-body{

		font-size: 14px;
	}

	@media screen and (max-width: 900px){
		.post-container{
			width: 95%;
		}
	}
</style>

<div class="post-container">

	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Retour aux articles</a>

	{% if request.user.is_staff %}
		 <a class="btn btn-sm btn-primary" href="{% url 'update_post' post.slug %}">Edit</a>
		 <a class="btn btn-sm btn-danger" href="{% url 'delete_post' post.slug %}">Delete</a>
	{% endif %}

	<img class="featured_image" src="{{post.thumbnail.url}}">

	{% for tag in post.tags.all %}
		<span class="tag">{{tag}}</span>
	{% endfor %}
	<hr>

	<h1>{{post.headline}}</h1>
	<h4>{{post.sub_headline}}</h4>
	<br>

	<p>{{post.body|safe}}</p>

	<div class="comments-wrapper">
		<h5>Comments: {{post.postcomment_set.all.count}}</h5>
		<hr>
		<!--
			- Not logged in, output form and say "Register to comment and give room for a message"
			- When given username
		-->
		{% if request.user.is_authenticated %}
		<form action="" method="POST">
			{% csrf_token %}
			<textarea required class="form-control" placeholder="Leave a comment..." name="comment"></textarea>
			<br>
			<input class="btn btn-info" type="submit" value="Submit">
		</form>
		{% else %}
			<p>Créez un compte pour commenter:</p>
			<a class="btn btn-primary" href="{% url 'register' %}">Register/Login</a>
		{% endif %}

		<hr>
		{% for comment in post.postcomment_set.all %}
			<div class="comment">
				<img class="author-pic" src="{{comment.author.profile_pic.url}}">
				<div>
					<p class="comment-author">{{comment.author}}: {{comment.created|date:"M-d-Y"}}</p>
					<p class="comment-body">{{comment.body}}</p>
				</div>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

ali/base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 100px;
		border-radius: 5px;
		padding: 5px;
		border:1px solid #888;
	}
</style>

<div class="main-container">
	<h1>Posts</h1>
	{% if request.user.is_staff %}
		<a class="btn btn-warning" href="{% url 'create_post' %}">Create Post / Ecrire un message </a>
	{% endif %}
	<form id="searchForm" method="GET">
		{{myFilter.form|crispy}}

		<input class="btn btn-primary" type="submit" value="search">
	</form>
	<br>
	<div class="post-wrapper">

		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">
					<h6 class="post-title">{{post.headline}}</h6>
					<p class="post-intro">{{post.sub_headline}}</p>
					<a href="{% url 'post' post.slug %}">Read More</a>

					{% if request.user.is_staff %}
						| <a href="{% url 'update_post' post.slug %}">Edit</a>
						| <a href="{% url 'delete_post' post.slug %}">Delete</a>
					{% endif %}
					<hr>
					{% for tag in post.tags.all %}
						<span class="tag">{{tag}}</span>
					{% endfor %}
				</div>
			</div>
		</div>
		{% empty %}
			<h3>Aucun article trouvé...</h3>
		{% endfor %}
	</div>

	<div class="row">

		{% if posts.has_other_pages %}

			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
					{% endif %}

				{% endfor %}


				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
				{% endif %}
			</ul>

		{% endif %}
	</div>
</div>


<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>

{% endblock content %}

ali/base/templates/base/profile_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="main-container">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input class="btn btn-primary" type="submit" value="Save">
	</form>
</div>
{% endblock content %}